#!/bin/bash
set -e
# Run Open-Vocabulary 3D Labeller pipeline for segmentation labels

# Set input file paths and prompts here
#VOXEL_FILE="/home/neural_fields/Unified-Lift-Gabor/cuda_project_image_to_sparse_voxel/voxel_feature_checkpoints_vox27522_mesh/ALL_nonzero_voxel_features_232_vox263500.pt"         # Change to your voxel feature file
#VOXEL_FILE="/home/neural_fields/Unified-Lift-Gabor/cuda_project_image_to_sparse_voxel/voxel_feature_checkpoints_vox96741_filtered/ALL_nonzero_voxel_features_232_vox96741.pt"         # Change to your voxel feature file
VOXEL_FILE="/home/neural_fields/Unified-Lift-Gabor/cuda_project_image_to_sparse_voxel/voxel_feature_checkpoints_vox195120_NEW/ALL_nonzero_voxel_features_216_vox16345680.pt"


#GAUSSIAN_PLY="/home/neural_fields/gaussian-splatting/output/cc946f8b-f/point_cloud/iteration_45000/point_cloud.ply"   # Input .ply file with Gaussian properties
GAUSSIAN_PLY="/home/neural_fields/gaussian-splatting/output/39ac5c9a-1/point_cloud/iteration_30000/point_cloud.ply"
#GAUSSIAN_PLY="/home/neural_fields/gaussian-splatting/output/f79056cd-8/point_cloud/iteration_40000/point_cloud.ply"
#GAUSSIAN_PLY="/home/neural_fields/gaussian-splatting/output/237ab5b3-5/point_cloud/iteration_80000/point_cloud.ply"
# GAUSSIAN_PLY="/home/neural_fields/Unified-Lift-Gabor/betterGaussians/filtered_gaussians.ply"   # Input .ply file with Gaussian properties

GAUSSIAN_FILE="/home/neural_fields/Unified-Lift-Gabor/voxel_to_gaussian/gaussians_pos.npy"   # Output file for extracted centers
MAP_FILE="/home/neural_fields/Unified-Lift-Gabor/voxel_to_gaussian/gauss2voxel.npy"      # Will be generated by build_map
OUT_DIR="/home/neural_fields/Unified-Lift-Gabor/voxel_to_gaussian/semantics_195120_30000_NEW" # Directory for output files
LABELS_OUT="/home/neural_fields/Unified-Lift-Gabor/voxel_to_gaussian/gaussian_semantics_filt_gauss_195120_30000_NEW.npz" # Output file for per-Gaussian labels
PROMPTS=("chair" "cabinet" "window" "wall" "door" "keyboard" "ceiling" "floor" "table" "laptop" "paper" "light" "monitor")

DEVICE="cuda"                            # "cuda" or "cpu"

mkdir -p "$OUT_DIR"

echo "[Step 0] Extract Gaussian centers from .ply"
python3 /home/neural_fields/Unified-Lift-Gabor/voxel_to_gaussian/extract_gaussian_centers.py \
    --ply "$GAUSSIAN_PLY" \
    --out "$GAUSSIAN_FILE"

echo "[Step 1] Build map (Gaussian → nearest voxel)"
python3 /home/neural_fields/Unified-Lift-Gabor/voxel_to_gaussian/voxeltoGaussian.py build_map \
    --vox "$VOXEL_FILE" \
    --gauss "$GAUSSIAN_FILE" \
    --out "$MAP_FILE"

echo "[Step 2] Query (assign semantic logits)"
python3 /home/neural_fields/Unified-Lift-Gabor/voxel_to_gaussian/voxeltoGaussian_logits.py query \
    --vox "$VOXEL_FILE" \
    --map "$MAP_FILE" \
    --prompt "${PROMPTS[@]}" \
    --out "$LABELS_OUT" \
    --device "$DEVICE" \
    --gauss "$GAUSSIAN_FILE"

echo "Pipeline complete. Output: $LABELS_OUT (contains per-Gaussian semantic labels and logits)"