wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1742729284.853913
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 105
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 105
      3:
      - 17
      - 19
      - 23
      - 37
      4: 3.8.18
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
args:
  desc: null
  value: Namespace(checkpoint_iterations=[], compute_cov3D_python=False, config_file='config/gaussian_dataset/train.json',
    convert_SHs_python=False, data_device='cuda', debug=False, debug_from=-1, densification_interval=100,
    densify_from_iter=500, densify_grad_threshold=0.0002, densify_until_iter=10000,
    detect_anomaly=False, eval=False, feature_lr=0.0025, images='images', ip='127.0.0.1',
    iterations=30000, lambda_dssim=0.2, model_path='./output/Unifed_lift//figurines',
    n_views=100, num_classes=256, object_path='object_mask', opacity_lr=0.05, opacity_reset_interval=3000,
    percent_dense=0.01, port=6009, position_lr_delay_mult=0.01, position_lr_final=1.6e-06,
    position_lr_init=0.00016, position_lr_max_steps=30000, quiet=False, random_init=False,
    reg3d_interval=5, reg3d_k=5, reg3d_lambda_val=2, reg3d_max_points=200000, reg3d_sample_size=1000,
    resolution=-1, rotation_lr=0.001, save_iterations=[100, 1000, 7000, 20000, 30000,
    60000, 30000], scaling_lr=0.005, sh_degree=3, source_path='/research/d1/gds/rszhu22/gaussian-grouping/data/lerf/figurines',
    start_checkpoint=None, test_iterations=[1000, 7000, 30000, 30000], train_split=True,
    use_wandb=True, weight_loss=1.0, white_background=False)
