#!/bin/bash
# Run Gaussian Color Assignment Pipeline

# Set input file paths here
VOXEL_COLOR_FILE="/home/neural_fields/Unified-Lift-Gabor/cuda_project_image_to_sparse_voxel/voxel_color_checkpoints_vox41759/ALL_nonzero_voxel_colors_232.pt"  # Voxel colors
GAUSSIAN_PLY="/home/neural_fields/gaussian-splatting/output/cc946f8b-f/point_cloud/iteration_45000/point_cloud.ply"   # Input .ply file with Gaussian properties
GAUSSIAN_FILE="/home/neural_fields/Unified-Lift-Gabor/voxel_to_gaussian/color/gaussians_pos.npy"   # Output file for extracted centers
MAP_FILE="/home/neural_fields/Unified-Lift-Gabor/voxel_to_gaussian/color/gauss2voxel.npy"      # Will be generated by build_map
COLOR_OUT="/home/neural_fields/Unified-Lift-Gabor/voxel_to_gaussian/color/gaussian_colors.npz" # Output file for per-Gaussian colors

# Step 0: Extract Gaussian centers from .ply
python3 /home/neural_fields/Unified-Lift-Gabor/voxel_to_gaussian/extract_gaussian_centers.py \
    --ply "$GAUSSIAN_PLY" \
    --out "$GAUSSIAN_FILE"


# Step 1: Build map (Gaussian → nearest voxel)
python3 /home/neural_fields/Unified-Lift-Gabor/voxel_to_gaussian/color/voxeltoGaussian_color.py build_map \
    --vox "$VOXEL_COLOR_FILE" \
    --gauss "$GAUSSIAN_FILE" \
    --out "$MAP_FILE"

# Step 2: Assign colors
python3 /home/neural_fields/Unified-Lift-Gabor/voxel_to_gaussian/color/voxeltoGaussian_color.py assign_color \
    --vox "$VOXEL_COLOR_FILE" \
    --map "$MAP_FILE" \
    --out "$COLOR_OUT"

echo "Color assignment pipeline complete. Output: $COLOR_OUT"
